# Generated by Django 5.2.3 on 2025-07-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_Portail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Email Log', 'verbose_name_plural': 'Email Logs'},
        ),
        migrations.AddField(
            model_name='messagelog',
            name='sender_email',
            field=models.EmailField(default='unknown@example.com', max_length=254, verbose_name="Student's Email"),
            preserve_default=False,
        ),
    ]
